#!/usr/bin/env python3
"""Validate a SKILL.md: UTF-8, YAML frontmatter, required keys, name/dir match.

Skills are silently dropped by the harness when their frontmatter is invalid, and
the model then cannot tell "absent" from "broken". This makes that failure loud.

Usage:
    python check_skills.py                     # $DSH_HOME/skills
    python check_skills.py <dir> [<dir> ...]   # specific roots
"""

from __future__ import annotations

import os
import re
import sys
from pathlib import Path

#: Default to the skills that SHIP with the plugin. It previously defaulted to
#: $DSH_HOME/skills, so the documented command `python tools/check_skills.py`
#: validated the user's own copies and never looked at the vendored ones — and the
#: two can differ (they are separate files, regenerated by vendor_skills.py). A
#: check that inspects something other than its stated subject is worse than no
#: check, because it reports a pass.
VENDORED = Path(__file__).resolve().parent.parent / "skills"
DEFAULT_ROOT = VENDORED if VENDORED.is_dir() else (
    Path(os.environ.get("DSH_HOME") or (Path.home() / ".dsh")) / "skills")


def check(skill_md: Path) -> bool:
    print(f"=== {skill_md.parent.name} ===")
    raw = skill_md.read_bytes()
    try:
        txt = raw.decode("utf-8")
    except UnicodeDecodeError as exc:
        print(f"  FAIL not valid UTF-8: {exc}")
        return False
    print(f"  size      : {len(raw):,} bytes / {len(txt):,} chars")
    print(f"  bom       : {raw[:3] == b'\xef\xbb\xbf'}")

    fm = re.match(r"^---\r?\n(.*?)\r?\n---\r?\n", txt, re.S)
    if not fm:
        print("  FAIL no YAML frontmatter")
        return False
    block = fm.group(1)

    ok = True
    for key in ("name", "description"):
        m = re.search(rf"^{key}:\s*(.+)$", block, re.M)
        if not m:
            print(f"  FAIL missing {key}")
            ok = False
            continue
        val = m.group(1).strip().strip('"')
        print(f"  {key:11}: {val[:66]}{'...' if len(val) > 66 else ''}")

    m = re.search(r"^name:\s*(\S+)", block, re.M)
    if m:
        expect = skill_md.parent.name
        if m.group(1) != expect:
            print(f"  FAIL name {m.group(1)!r} != directory {expect!r}")
            ok = False
        else:
            print("  name/dir  : match")

    print(f"  whenToUse : {'present' if re.search(r'^whenToUse:', block, re.M) else '(absent, optional)'}")
    print(f"  body      : {len(txt) - fm.end():,} chars")
    print(f"  headings  : {len(re.findall(r'^## ', txt, re.M))}")
    print("  RESULT    : " + ("OK" if ok else "PROBLEMS"))
    return ok


def main() -> int:
    roots = [Path(a) for a in sys.argv[1:]] or [DEFAULT_ROOT]
    found: list[Path] = []
    for root in roots:
        if not root.is_dir():
            print(f"! not a directory: {root}")
            continue
        found.extend(sorted(root.glob("*/SKILL.md")))
        found.extend(sorted(root.glob("*.md")))
    if not found:
        print("no skills found")
        return 1
    results = [check(p) for p in found]
    print(f"\n{sum(results)}/{len(results)} skill(s) valid")
    return 0 if all(results) else 1


if __name__ == "__main__":
    raise SystemExit(main())
